from unittest.mock import MagicMock

stats_mock = MagicMock()
stats_mock.count = 'randomvalue'
stats_mock.index = 'randomvalue'
stats_mock.n_fields = 'randomvalue'
stats_mock.n_sequence_fields = 'randomvalue'
stats_mock.n_unnamed_fields = 'randomvalue'
stats_mock.st_atime = 'randomvalue'
stats_mock.st_atime_ns = 'randomvalue'
stats_mock.st_birthtime = 'randomvalue'
stats_mock.st_blksize = 'randomvalue'
stats_mock.st_blocks = 'randomvalue'
stats_mock.st_ctime = 'randomvalue'
stats_mock.st_ctime_ns = 'randomvalue'
stats_mock.st_dev = 'randomvalue'
stats_mock.st_flags = 'randomvalue'
stats_mock.st_gen = 'randomvalue'
stats_mock.st_gid = 'randomvalue'
stats_mock.st_ino = 'randomvalue'
stats_mock.st_mode = 'randomvalue'
stats_mock.st_mtime = 'randomvalue'
stats_mock.st_mtime_ns = 'randomvalue'
stats_mock.st_nlink = 'randomvalue'
stats_mock.st_rdev = 'randomvalue'
stats_mock.st_size = 'randomvalue'
stats_mock.st_ui = 'randomvalue'